dist: trusty
sudo: required

language: cpp

sudo: false

before_install:
  - sudo apt-get install -y libopenblas-dev
  - sudo apt-get install -y liblapack-dev
  - sudo apt-get install -y libarpack-dev
  - wget http://sourceforge.net/projects/arma/files/armadillo-9.100.5.tar.xz
  - tar xf armadillo*
  - cd armadillo*
  - cmake . && make && sudo make install && cd ..
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

install:
  - "./configure"
  - "make"
  - "make install"

script:
  - "./test/launch_tests.sh"

