
{% set version = "0.1.0" %}

package:
  name: pairsnp
  version: 0.1.0

source:
  git_url: https://github.com/gtonkinhill/pairsnp-cpp

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - gcc_linux-64   # [not osx]
  host:
    - openblas
    - armadillo
  run:
    - libgcc    # [not osx]
    - openblas
    - armadillo

about:
  home: https://github.com/gtonkinhill/pairsnp-cpp
  license: MIT
  summary: "pairsnp calculates pairwise SNP distance matrices from multiple sequence alignment fasta files."
  license_file: LICENSE


test:
  commands:
    - pairsnp -h