name: pairsnp-cpp-CI

on:
  push:
    branches:
    - master
    - devel
  pull_request:
    branches:
    - master
    - devel
  schedule:
    - cron:  '1 1 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential
          
      - name: Install
        uses: actions/checkout@v2
        run: |
          make
          sudo make install

      - name: Validation Tests
        run: make check


